# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8876fae9d1e36321a027a94285539de5cab7bbbe8c5b4b58532c2249445e8fd8940292f7c91928e1b580a8be5e6c69d7e40e0ceac91cd0630a1b0c8157594c

test:
  secret_key_base: 5a2a00b98e3e41980af2f28bcd1621c5e8210f4c61b52297f6ad7e2586830c0c1763564a88a9f82b718b47327f8103d573e8a7d965133a5abfd034e8bf42eb5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
